Config = Config or {}

Config.WeaponAmmos = {
	[GetHashKey("weapon_pistol")]				= "9mm_ammo",
	[GetHashKey("weapon_pistol_mk2")]			= "9mm_ammo",
	[GetHashKey("weapon_combatpistol")]			= "9mm_ammo",
	[GetHashKey("weapon_appistol")]				= "9mm_ammo",
	[GetHashKey("weapon_pistol50")]				= "9mm_ammo",
	[GetHashKey("weapon_snspistol")]			= "9mm_ammo",
	[GetHashKey("weapon_snspistol_mk2")]		= "9mm_ammo",
	[GetHashKey("weapon_heavypistol")]			= "9mm_ammo",
	[GetHashKey("weapon_vintagepistol")]		= "9mm_ammo",
	[GetHashKey("weapon_ceramicpistol")]		= "9mm_ammo",
	[GetHashKey("weapon_gadgetpistol")]			= "9mm_ammo",
	[GetHashKey("weapon_pistolxm3")]			= "9mm_ammo",
	[GetHashKey("weapon_trainingpistol")]		= "9mm_ammo",
	[GetHashKey("weapon_flaregun")]				= "fuseededetresse",

	[GetHashKey("weapon_marksmanpistol")]		= "357_ammo",
	[GetHashKey("weapon_revolver")]				= "357_ammo",
	[GetHashKey("weapon_revolver_mk2")]			= "357_ammo",
	[GetHashKey("weapon_doubleaction")]			= "357_ammo",
	[GetHashKey("weapon_navyrevolver")]			= "357_ammo",

	[GetHashKey("weapon_microsmg")]				= "556_ammo",
	[GetHashKey("weapon_smg")]					= "556_ammo",
	[GetHashKey("weapon_smg_mk2")]				= "556_ammo",
	[GetHashKey("weapon_assaultsmg")]			= "556_ammo",
	[GetHashKey("weapon_combatpdw")]			= "556_ammo",
	[GetHashKey("weapon_machinepistol")]		= "556_ammo",
	[GetHashKey("weapon_minismg")]				= "556_ammo",
	[GetHashKey("weapon_tecpistol")]			= "556_ammo",
	[GetHashKey("weapon_carbinerifle")]			= "556_ammo",
	[GetHashKey("weapon_carbinerifle_mk2")]		= "556_ammo",

	[GetHashKey("weapon_pumpshotgun")]			= "12g_ammo",
	[GetHashKey("weapon_pumpshotgun_mk2")]		= "12g_ammo",
	[GetHashKey("weapon_sawnoffshotgun")]		= "12g_ammo",
	[GetHashKey("weapon_assaultshotgun")]		= "12g_ammo",
	[GetHashKey("weapon_bullpupshotgun")]		= "12g_ammo",
	[GetHashKey("weapon_musket")]				= "12g_ammo",
	[GetHashKey("weapon_heavyshotgun")]			= "12g_ammo",
	[GetHashKey("weapon_dbshotgun")]			= "12g_ammo",
	[GetHashKey("weapon_autoshotgun")]			= "12g_ammo",
	[GetHashKey("weapon_combatshotgun")]		= "12g_ammo",
	[GetHashKey("weapon_beanbag")]				= "12g_ammo",
	[GetHashKey("weapon_beanbag2")]				= "12g_ammo",

	[GetHashKey("weapon_assaultrifle")]			= "762_ammo",
	[GetHashKey("weapon_assaultrifle_mk2")]		= "762_ammo",
	[GetHashKey("weapon_advancedrifle")]		= "762_ammo",
	[GetHashKey("weapon_specialcarbine")]		= "762_ammo",
	[GetHashKey("weapon_specialcarbine_mk2")]	= "762_ammo",
	[GetHashKey("weapon_bullpuprifle")]			= "762_ammo",
	[GetHashKey("weapon_bullpuprifle_mk2")]		= "762_ammo",
	[GetHashKey("weapon_compactrifle")]			= "762_ammo",
	[GetHashKey("weapon_militaryrifle")]		= "762_ammo",
	[GetHashKey("weapon_heavyrifle")]			= "762_ammo",
	[GetHashKey("weapon_tacticalrifle")]		= "762_ammo",

	[GetHashKey("weapon_mg")]					= "556_ammo",
	[GetHashKey("weapon_combatmg")]				= "556_ammo",
	[GetHashKey("weapon_combatmg_mk2")]			= "556_ammo",
	[GetHashKey("weapon_gusenberg")]			= "556_ammo",

	[GetHashKey("weapon_sniperrifle")]			= "cal50_ammo",
	[GetHashKey("weapon_heavysniper")]			= "cal50_ammo",
	[GetHashKey("weapon_heavysniper_mk2")]		= "cal50_ammo",
	[GetHashKey("weapon_marksmanrifle")]		= "cal50_ammo",
	[GetHashKey("weapon_marksmanrifle_mk2")]	= "cal50_ammo",
	[GetHashKey("weapon_precisionrifle")]		= "cal50_ammo",

	[GetHashKey("weapon_40mmlesslethal")]		= "40mm_ammo",
	[GetHashKey("weapon_40mmlesslethal2")]		= "40mm_ammo",
}
