Config = Config or {}

Config.Weapons = {
	--MELEE
	["dague"]			= GetHashKey("weapon_dagger"),
	["battedebaseball"]	= GetHashKey("weapon_bat"),
	["tesson"]			= GetHashKey("weapon_bottle"),
	["pieddebiche"]		= GetHashKey("weapon_crowbar"),
	["flashlight"]		= GetHashKey("weapon_flashlight"),
	["clubgolf"]		= GetHashKey("weapon_golfclub"),
	["marteau"]			= GetHashKey("weapon_hammer"),
	["hachette"]		= GetHashKey("weapon_hatchet"),
	["poingamericain"]	= GetHashKey("weapon_knuckle"),
	["knife"]			= GetHashKey("weapon_knife"),
	["machette"]		= GetHashKey("weapon_machete"),
	["crandarret"]		= GetHashKey("weapon_switchblade"),
	["nightstick"]		= GetHashKey("weapon_nightstick"),
	["cleanglaise"]		= GetHashKey("weapon_wrench"),
	["hachecombat"]		= GetHashKey("weapon_battleaxe"),
	["queuebillard"]	= GetHashKey("weapon_poolcue"),
	["candycane"]		= GetHashKey("weapon_candycane"),

	--HANDGUN
	["beretta92"]		= GetHashKey("weapon_pistol"),
	["hkdp9"]			= GetHashKey("weapon_pistol_mk2"),
	["glock_17"]		= GetHashKey("weapon_combatpistol"),
	["stungun"]			= GetHashKey("weapon_stungun"),
	["deserteagle"]		= GetHashKey("weapon_pistol50"),
	["hkp7"]			= GetHashKey("weapon_snspistol"),
	["colt25"]			= GetHashKey("weapon_snspistol_mk2"),
	["shendurance"]		= GetHashKey("weapon_heavypistol"),
	["vintage"]			= GetHashKey("weapon_vintagepistol"),
	["flaregun"]		= GetHashKey("weapon_flaregun"),
	["pistolprecision"]	= GetHashKey("weapon_marksmanpistol"),
	["taurusrb"]		= GetHashKey("weapon_revolver"),
	["357_magnum"]		= GetHashKey("weapon_revolver_mk2"),
	["doubleaction"]	= GetHashKey("weapon_doubleaction"),
	["ceramicpistol"]	= GetHashKey("weapon_ceramicpistol"),
	["navyrevolver"]	= GetHashKey("weapon_navyrevolver"),
	["cayopistol"]		= GetHashKey("weapon_gadgetpistol"),
	["pistolxm3"]		= GetHashKey("weapon_pistolxm3"),

	--SMG
	["uzi"]				= GetHashKey("weapon_microsmg"),
	["hkmp5"]			= GetHashKey("weapon_smg"),
	["hkmp5mk2"]		= GetHashKey("weapon_smg_mk2"),
	["assaultsmg"]		= GetHashKey("weapon_assaultsmg"),
	["combatpdw"]		= GetHashKey("weapon_combatpdw"),
	["machinepistol"]	= GetHashKey("weapon_machinepistol"),
	["minismg"]			= GetHashKey("weapon_minismg"),
	["tecpistol"]		= GetHashKey("weapon_tecpistol"),

	--SHOTGUN
	["pumpshotgun"]		= GetHashKey("weapon_pumpshotgun"),
	["pumpshotgunmk2"]	= GetHashKey("weapon_pumpshotgun_mk2"),
	["sawnoffshotgun"]	= GetHashKey("weapon_sawnoffshotgun"),
	["assaultshotgun"]	= GetHashKey("weapon_assaultshotgun"),
	["bullpupshotgun"]	= GetHashKey("weapon_bullpupshotgun"),
	["mousquet"]		= GetHashKey("weapon_musket"),
	["heavyshotgun"]	= GetHashKey("weapon_heavyshotgun"),
	["dbshotgun"]		= GetHashKey("weapon_dbshotgun"),
	["autoshotgun"]		= GetHashKey("weapon_autoshotgun"),
	["combatshotgun"]	= GetHashKey("weapon_combatshotgun"),

	--ASSAULT
	["ak47"]			= GetHashKey("weapon_assaultrifle"),
	["ak47mk2"]			= GetHashKey("weapon_assaultrifle_mk2"),
	["coltm4a1"]		= GetHashKey("weapon_carbinerifle"),
	["carbinemk2"]		= GetHashKey("weapon_carbinerifle_mk2"),
	["advancedrifle"]	= GetHashKey("weapon_advancedrifle"),
	["g36c"]			= GetHashKey("weapon_specialcarbine"),
	["g36cmk2"]			= GetHashKey("weapon_specialcarbine_mk2"),
	["bullpup"]			= GetHashKey("weapon_bullpuprifle"),
	["bullpupmk2"]		= GetHashKey("weapon_bullpuprifle_mk2"),
	["ak74u"]			= GetHashKey("weapon_compactrifle"),
	["militaryrifle"]	= GetHashKey("weapon_militaryrifle"),
	["heavyrifle"]		= GetHashKey("weapon_heavyrifle"),
	["m16"]				= GetHashKey("weapon_tacticalrifle"),

	--LMG
	["mg"]				= GetHashKey("weapon_mg"),
	["combatmg"]		= GetHashKey("weapon_combatmg"),
	["combatmgmk2"]		= GetHashKey("weapon_combatmg_mk2"),
	["gusenberg"]		= GetHashKey("weapon_gusenberg"),

	--SNIPER
	["sniperrifle"]		= GetHashKey("weapon_sniperrifle"),
	["heavysniper"]		= GetHashKey("weapon_heavysniper"),
	["heavysnipermk2"]	= GetHashKey("weapon_heavysniper_mk2"),
	["marksmanrifle"]	= GetHashKey("weapon_marksmanrifle"),
	["marksmanriflemk2"]= GetHashKey("weapon_marksmanrifle_mk2"),
	["precisionrifle"]	= GetHashKey("weapon_precisionrifle"),

	--THROWABLES
	["gazbz"]			= GetHashKey("weapon_bzgas"),
	["molotov"]			= GetHashKey("weapon_molotov"),
	["c4bomb"]			= GetHashKey("weapon_stickybomb"),
	["snowball"]		= GetHashKey("weapon_snowball"),
	["balletennis"]		= GetHashKey("weapon_ball"),
	["smokegrenade"]	= GetHashKey("weapon_smokegrenade"),
	["flare"]			= GetHashKey("weapon_flare"),
	["acidpackage"]		= GetHashKey("weapon_acidpackage"),

	--MISC
	["bidonessence"]	= GetHashKey("weapon_petrolcan"),
	["parachute"]		= GetHashKey("gadget_parachute"),
	["extincteur"]		= GetHashKey("weapon_fireextinguisher"),
	["hazardcan"]		= GetHashKey("weapon_hazardcan"),
	["fertilizercan"]	= GetHashKey("weapon_fertilizercan"),

	--ADDONS
	["matraquetele"]	= GetHashKey("weapon_baton"),
	["beanbag"]			= GetHashKey("weapon_beanbag"),
	["beanbag2"]		= GetHashKey("weapon_beanbag2"),
	["empty_can"]		= GetHashKey("weapon_canette"),
	["flashball"]		= GetHashKey("weapon_40mmlesslethal"),
	["flashball2"]		= GetHashKey("weapon_40mmlesslethal2"),
	["trainingpistol"]	= GetHashKey("weapon_trainingpistol"),
	["stungun2"]		= GetHashKey("weapon_stungun2"),
	["flashbang"]		= GetHashKey("weapon_flashbang"),
	["sledgehammer"]	= GetHashKey("weapon_sledgehammer"),
	["halligan"]		= GetHashKey("weapon_halligan"),
	["pikepole"]		= GetHashKey("weapon_pikepole"),
	["hydrantwrench"]	= GetHashKey("weapon_hydrantwrench"),
	["fireaxe"]			= GetHashKey("weapon_fireaxe"),
	["katana"]			= GetHashKey("weapon_katana"),
	["pickaxe"]			= GetHashKey("weapon_pickaxe"),
	["pepperspray"]		= GetHashKey("weapon_pepperspray"),
	["antidot"]			= GetHashKey("weapon_antidote"),
	["paintball"]		= GetHashKey("weapon_paintball"),
}

Config.WeaponMags = {
	"munitionflare",
	"cal50_ammo",
	"40mm_ammo",
	"9mm_ammo",
	"357_ammo",
	"556_ammo",
	"12g_ammo",
	"762_ammo",
}
