MainMenu = MainMenu or {}
MainMenu.Props = MainMenu.Props or {}

local lists = {
	["Chambre"] = {
		["pata_artwall"] = "Tableau 1",
		["pata_artwall2"] = "Tableau 2",
		["pata_artwall3"] = "Tableau 3",
		["pata_bedroom1"] = "Lit",
		["pata_bedroom2"] = "Bibliothèque 4",
		["pata_bedroom3"] = "Meuble TV",
		["pata_bedroom4"] = "Table de nuit",
		["pata_bedroom5"] = "Table basse",
		["pata_bedroom6"] = "Lampe de chevet",
		["pata_bedroom7"] = "Commode",
		["pata_bedroom8"] = "Chaise",
		["pata_bedroom9"] = "Radiateur",
		["pata_bedroom10"] = "Tapis",
		["pata_bedroom11"] = "Pouf",
		["pata_bedroom12"] = "Bureau",
		["pata_bedroom13"] = "Chaise",
		["pata_bedroom14"] = "Penderie",
		["pata_bedroom15"] = "Bibliothèque 2",
		["pata_bedroom16"] = "Lit 2",
		["pata_bedroom17"] = "Tête de lit",
		["pata_bedroom18"] = "Lit 3",
		["pata_bedroom19"] = "Table de nuit 2",
		["pata_bedroom20"] = "Tête de lit 2",
		["pata_bedroom21"] = "Pot de branche",
		["pata_bedroom22"] = "Lit 4",
		["pata_bedroom23"] = "Pendule",
		["pata_biblio3"] = "Bibliothèque 3",
	},
	["Nourriture"] = {
		["pata_food1"] = "Pain",
		["pata_food2"] = "Tiramisu",
		["pata_food3"] = "Tiramisu Framboise",
		["pata_food4"] = "Muffin",
		["pata_food5"] = "Sandwich Croissant",
		["pata_food6"] = "Sandwich",
		["pata_food7"] = "Fish & Chips",
		["pata_food8"] = "Wing",
		["pata_food9"] = "Club Sandwich",
		["pata_food10"] = "Burger Poulet",
		["pata_food11"] = "Calzone",
		["pata_food12"] = "Pizza Jambon Champignon",
		["pata_food13"] = "Crepe Caramel",
		["pata_food14"] = "Salade",
		["pata_food15"] = "Wrap + Salade",
		["pata_food16"] = "Salade 2",
		["pata_food17"] = "Wrap + Patatoes",
		["pata_food18"] = "Crêpe Chocolat",
		["pata_food19"] = "Crêpe + Glace",
		["pata_food20"] = "Poké-Bowl",
	},
	["Meubles"] = {
		["gcom_dec_pack_bathcab"] = "Meuble de salle de bain",
		["gcom_dec_pack_cabinet"] = "Commode",
		["gcom_dec_pack_cabinet_2"] = "Commode 2",
		["gcom_dec_pack_table_1"] = "Table 1",
		["gcom_dec_pack_table_2"] = "Table 2",
		["gcom_dec_pack_wall"] = "Étagère",
		["gcom_dec_pack_wardrobe_1"] = "Garde-Robe 1",
		["gcom_dec_pack_wardrobe_2"] = "Garde-Robe 2",
		["murm_dec_pack_cabinet"] = "Commode 3",
		["murm_dec_pack_chair_1"] = "Chaise 1",
		["murm_dec_pack_chair_2"] = "Chaise 2",
		["murm_dec_pack_dresser"] = "Commode 4",
		["murm_dec_pack_sofa"] = "Sofa",
		["murm_dec_pack_table"] = "Table 3",
	},
	["Jardin"] = {
		["pata_garden2"] = "Table",
		["pata_garden3"] = "Pot de plante",
		["pata_garden4"] = "Livre + Bougie",
		["pata_garden5"] = "Table basse de jardin",
		["pata_garden6"] = "Bougie 2",
		["pata_garden7"] = "Ruche",
		["pata_garden8"] = "Chaise 4",
		["pata_garden9"] = "Table 2",
		["pata_garden10"] = "Pot de fleur suspendu",
		["pata_garden11"] = "Barbecue",
		["pata_garden12"] = "Lampe de jardin",
		["pata_garden13"] = "Pot de fleur",
		["pata_garden14"] = "Chaise",
		["pata_garden15"] = "Canapé",
		["pata_garden16"] = "Magazine + Chapeau",
		["pata_garden17"] = "Bougie",
		["pata_garden18"] = "Pot de fleur 2",
		["pata_garden19"] = "Pot de fleur 3",
		["pata_garden20"] = "Pergola",
		["pata_garden21"] = "Chaise 2",
		["pata_garden22"] = "Plateau",
		["pata_garden23"] = "Chaise en rondin",
		["pata_garden24"] = "Jacuzzi",
		["pata_garden25"] = "Guirlande de lumière",
		["pata_garden26"] = "Balançoire",
		["pata_garden27"] = "Canapé 2",
		["pata_garden28"] = "Chaise 3",
		["pata_garden29"] = "Bibliothèque de jardin",
		["pata_garden30"] = "Commode de jardin",
		["pata_garden31"] = "Banc de jardin",
		["pata_garden32"] = "Rosier",
		["pata_garden33"] = "Arche fleuri",
		["pata_garden34"] = "Pergola fleuri",
		["pata_garden35"] = "Arbre",
		["pata_garden36"] = "Fleur",
		["pata_garden37"] = "Petit arbre",
		["pata_garden38"] = "Arche en fleur",
		["pata_garden39"] = "Saule pleureur",
		["pata_garden40"] = "Toilette de jardin",
		["pata_garden41"] = "Fleur 2",
		["pata_garden42"] = "Arche",
		["pata_garden43"] = "Fleur 3",
		["pata_garden44"] = "Buisson",
		["pata_garden45"] = "Cloture",
		["pata_garden46"] = "Transat en bambou",
		["pata_garden47"] = "Cerisier",
		["pata_garden48"] = "Tronc + Oiseaux",
		["pata_garden49"] = "Bambou",
		["pata_garden50"] = "Fleur 4",
		["pata_garden51"] = "Fleur 5",
	},
	["Bureau"] = {
		["pata_office1"] = "Ordinateur Fixe",
		["pata_office2"] = "Ordinateur Fixe 2",
		["pata_office3"] = "Chaise Gaming",
		["pata_office4"] = "Lampe Pacman",
		["pata_office5"] = "Enceinte",
		["pata_office6"] = "Chaise Gaming 2",
		["pata_office7"] = "Appareil Photo (webcam)",
		["pata_office8"] = "Lumière Led",
		["pata_office9"] = "Micro sur bras",
		["pata_office10"] = "Bureau",
		["pata_office11"] = "Neon",
		["pata_office12"] = "Neon 2",
		["pata_officeclassic1"] = "Bureau 2",
		["pata_officeclassic2"] = "Bureau d'angle",
		["pata_officeclassic3"] = "Chevalet d'architecte",
		["pata_officeclassic4"] = "Rangement",
		["pata_officeclassic5"] = "Casier de rangement",
		["pata_officeclassic6"] = "Chaise de bureau 2",
		["pata_officeclassic7"] = "Chaise de bureau 3",
		["pata_officeclassic8"] = "Bibliothèque 3",
		["pata_officeclassic9"] = "Chaise surélevé",
		["pata_officeclassic10"] = "Papier (Plan)",
		["pata_officeclassic11"] = "Ordinateur Portable",
		["pata_officeclassic12"] = "Pot de crayons",
		["pata_officeclassic13"] = "Bureau (accroché au mur)",
		["pata_officeclassic14"] = "Bibliothèque",
		["pata_officeclassic15"] = "Pot de fleur",
		["pata_officeclassic16"] = "Cahiers",
		["pata_officeclassic17"] = "Commode",
		["pata_officeclassic18"] = "Rangement au mur",
		["pata_officeclassic19"] = "Rangement au mur 2",
		["pata_officeclassic20"] = "Bibliothèque 2",
		["pata_officeclassic21"] = "Chaise de bureau",
		["pata_officeclassic22"] = "Etagère",
		["pata_officeclassic23"] = "Poubelle",
		["pata_pinkoffice1"] = "Ordinateur fixe (rose)",
		["pata_pinkoffice2"] = "Chat endormi",
		["pata_pinkoffice3"] = "Pot de fleur",
		["pata_pinkoffice4"] = "Pot de fleur 2",
		["pata_pinkoffice5"] = "Gobelet de café",
		["pata_pinkoffice6"] = "Bureau 2 (rose)",
		["pata_pinkoffice7"] = "Cahier (rose)",
		["pata_pinkoffice8"] = "Cahier 2 (rose)",
		["pata_pinkoffice9"] = "Chaise de bureau (rose)",
		["pata_pinkoffice10"] = "Tablette (rose)",
		["pata_pinkoffice11"] = "Pot a crayons (rose)",
		["pata_pinkoffice12"] = "Tableau d'affichage (rose)",
		["pata_pinkoffice13"] = "Bureau (rose)",
		["pata_pinkoffice14"] = "Casier (rose)",
	},
	["Animaux"] = {
		["pata_pet1"] = "Gamelle Os",
		["pata_pet10"] = "Vivarium",
		["pata_pet11"] = "Commode",
		["pata_pet12"] = "Commode 2",
		["pata_pet13"] = "Peluche Furet",
		["pata_pet14"] = "Peluche Cochon d'inde",
		["pata_pet15"] = "Peluche Souris Blanche",
		["pata_pet16"] = "Peluche Souris Noire",
		["pata_pet17"] = "Terrarium",
		["pata_pet18"] = "Cage 1",
		["pata_pet19"] = "Cage 2",
		["pata_pet2"] = "Porte Laisse",
		["pata_pet20"] = "Rangement",
		["pata_pet21"] = "Lit Caravane",
		["pata_pet22"] = "Litiere Chat",
		["pata_pet23"] = "Arbre à chat (bois)",
		["pata_pet24"] = "Lit Tipi",
		["pata_pet25"] = "Niche",
		["pata_pet26"] = "Panneau",
		["pata_pet27"] = "Etagère Chien",
		["pata_pet28"] = "Panier suspendu",
		["pata_pet29"] = "Panier 2",
		["pata_pet3"] = "Panier 3",
		["pata_pet30"] = "Panier Commode",
		["pata_pet31"] = "Panier Commode 2",
		["pata_pet32"] = "Shampooing pour chien",
		["pata_pet33"] = "Commode 3",
		["pata_pet34"] = "Panier 4",
		["pata_pet35"] = "Gamelle",
		["pata_pet36"] = "Gamelle Chat",
		["pata_pet37"] = "Distributeur à croquette",
		["pata_pet38"] = "Gamelle 2",
		["pata_pet39"] = "Arbre à chat 2 (bois)",
		["pata_pet4"] = "Panier Sapin",
		["pata_pet40"] = "Maison pour chat",
		["pata_pet41"] = "Niche 2",
		["pata_pet42"] = "Litière",
		["pata_pet43"] = "Lampe Chat",
		["pata_pet44"] = "Porte Laisse Os",
		["pata_pet45"] = "Griffoir",
		["pata_pet46"] = "Decoration Chat",
		["pata_pet47"] = "Decoration Chien",
		["pata_pet48"] = "Plante suspendu 1",
		["pata_pet49"] = "Lit Suspendu",
		["pata_pet5"] = "Gamelle Sapin",
		["pata_pet50"] = "Plante suspendu 2",
		["pata_pet51"] = "Arbre à chat 3",
		["pata_pet52"] = "Canapé",
		["pata_pet53"] = "Panier TV",
		["pata_pet54"] = "Siege Cocoon",
		["pata_pet55"] = "Lustre Girafe",
		["pata_pet56"] = "Bibliothèque",
		["pata_pet57"] = "Fauteuil Chat",
		["pata_pet58"] = "Table",
		["pata_pet59"] = "Pouf Patte",
		["pata_pet6"] = "Pont Suspendu",
		["pata_pet60"] = "Plante",
		["pata_pet61"] = "Chaise",
		["pata_pet62"] = "TV",
		["pata_pet7"] = "Panier Cagette",
		["pata_pet8"] = "Cage à oiseaux",
		["pata_pet9"] = "Vivarium 2",
	},
	["Murs & Sols"] = {
		["doorwall01"] = "Mur (porte) 1",
		["doorwall02"] = "Mur (porte) 2",
		["doorwall03"] = "Mur (porte) 3",
		["doorwall04"] = "Mur (porte) 4",
		["doorwall05"] = "Mur (porte) 5",
		["doorwall06"] = "Mur (porte) 6",
		["doorwall07"] = "Mur (porte) 7",
		["doorwall08"] = "Mur (porte) 8",
		["doorwall09"] = "Mur (porte) 9",
		["doorwall10"] = "Mur (porte) 10",
		["doorwall11"] = "Mur (porte) 11",
		["doorwall12"] = "Mur (porte) 12",
		["doorwall13"] = "Mur (porte) 13",
		["doorwall14"] = "Mur (porte) 14",
		["doorwall15"] = "Mur (porte) 15",
		["doorwall16"] = "Mur (porte) 16",
		["doorwall17"] = "Mur (porte) 17",
		["doorwall18"] = "Mur (porte) 18",
		["doorwall19"] = "Mur (porte) 19",
		["doorwall20"] = "Mur (porte) 20",
		["doorwall21"] = "Mur (porte) 21",
		["doorwall22"] = "Mur (porte) 22",
		["doorwall23"] = "Mur (porte) 23",
		["doorwall24"] = "Mur (porte) 24",
		["doorwall25"] = "Mur (porte) 25",
		["doorwall26"] = "Mur (porte) 26",
		["doorwall27"] = "Mur (porte) 27",
		["doorwall28"] = "Mur (porte) 28",
		["doorwall29"] = "Mur (porte) 29",
		["doorwall30"] = "Mur (porte) 30",
		["doorwall31"] = "Mur (porte) 31",
		["doorwall32"] = "Mur (porte) 32",
		["doorwall33"] = "Mur (porte) 33",
		["doorwall34"] = "Mur (porte) 34",
		["doorwall35"] = "Mur (porte) 35",
		["doorwall36"] = "Mur (porte) 36",
		["doorwall37"] = "Mur (porte) 37",
		["doorwall38"] = "Mur (porte) 38",
		["doorwall39"] = "Mur (porte) 39",
		["doorwall40"] = "Mur (porte) 40",
		["floor01"] = "Sol 1",
		["floor02"] = "Sol 2",
		["floor03"] = "Sol 3",
		["floor04"] = "Sol 4",
		["floor05"] = "Sol 5",
		["floor06"] = "Sol 6",
		["floor07"] = "Sol 7",
		["floor08"] = "Sol 8",
		["floor09"] = "Sol 9",
		["floor10"] = "Sol 10",
		["floor11"] = "Sol 11",
		["floor12"] = "Sol 12",
		["floor13"] = "Sol 13",
		["floor14"] = "Sol 14",
		["floor15"] = "Sol 15",
		["floor16"] = "Sol 16",
		["floor17"] = "Sol 17",
		["floor18"] = "Sol 18",
		["floor19"] = "Sol 19",
		["floor20"] = "Sol 20",
		["floor21"] = "Sol 21",
		["floor22"] = "Sol 22",
		["floor23"] = "Sol 23",
		["floor24"] = "Sol 24",
		["floor25"] = "Sol 25",
		["floor26"] = "Sol 26",
		["floor27"] = "Sol 27",
		["floor28"] = "Sol 28",
		["floor29"] = "Sol 29",
		["floor30"] = "Sol 30",
		["halfwall01"] = "Mur (demi) 1",
		["halfwall02"] = "Mur (demi) 2",
		["halfwall03"] = "Mur (demi) 3",
		["halfwall04"] = "Mur (demi) 4",
		["halfwall05"] = "Mur (demi) 5",
		["halfwall06"] = "Mur (demi) 6",
		["halfwall07"] = "Mur (demi) 7",
		["halfwall08"] = "Mur (demi) 8",
		["halfwall09"] = "Mur (demi) 9",
		["halfwall10"] = "Mur (demi) 10",
		["halfwall11"] = "Mur (demi) 11",
		["halfwall12"] = "Mur (demi) 12",
		["halfwall13"] = "Mur (demi) 13",
		["halfwall14"] = "Mur (demi) 14",
		["halfwall15"] = "Mur (demi) 15",
		["halfwall16"] = "Mur (demi) 16",
		["halfwall17"] = "Mur (demi) 17",
		["halfwall18"] = "Mur (demi) 18",
		["halfwall19"] = "Mur (demi) 19",
		["halfwall20"] = "Mur (demi) 20",
		["halfwall21"] = "Mur (demi) 21",
		["halfwall22"] = "Mur (demi) 22",
		["halfwall23"] = "Mur (demi) 23",
		["halfwall24"] = "Mur (demi) 24",
		["halfwall25"] = "Mur (demi) 25",
		["halfwall26"] = "Mur (demi) 26",
		["halfwall27"] = "Mur (demi) 27",
		["halfwall28"] = "Mur (demi) 28",
		["halfwall29"] = "Mur (demi) 29",
		["halfwall30"] = "Mur (demi) 30",
		["halfwall31"] = "Mur (demi) 31",
		["halfwall32"] = "Mur (demi) 32",
		["halfwall33"] = "Mur (demi) 33",
		["halfwall34"] = "Mur (demi) 34",
		["halfwall35"] = "Mur (demi) 35",
		["halfwall36"] = "Mur (demi) 36",
		["halfwall37"] = "Mur (demi) 37",
		["halfwall38"] = "Mur (demi) 38",
		["halfwall39"] = "Mur (demi) 39",
		["halfwall40"] = "Mur (demi) 40",
		["longwall01"] = "Mur (long) 1",
		["longwall02"] = "Mur (long) 2",
		["longwall03"] = "Mur (long) 3",
		["longwall04"] = "Mur (long) 4",
		["longwall05"] = "Mur (long) 5",
		["longwall06"] = "Mur (long) 6",
		["longwall07"] = "Mur (long) 7",
		["longwall08"] = "Mur (long) 8",
		["longwall09"] = "Mur (long) 9",
		["longwall10"] = "Mur (long) 10",
		["longwall11"] = "Mur (long) 11",
		["longwall12"] = "Mur (long) 12",
		["longwall13"] = "Mur (long) 13",
		["longwall14"] = "Mur (long) 14",
		["longwall15"] = "Mur (long) 15",
		["longwall16"] = "Mur (long) 16",
		["longwall17"] = "Mur (long) 17",
		["longwall18"] = "Mur (long) 18",
		["longwall19"] = "Mur (long) 19",
		["longwall20"] = "Mur (long) 20",
		["longwall21"] = "Mur (long) 21",
		["longwall22"] = "Mur (long) 22",
		["longwall23"] = "Mur (long) 23",
		["longwall24"] = "Mur (long) 24",
		["longwall25"] = "Mur (long) 25",
		["longwall26"] = "Mur (long) 26",
		["longwall27"] = "Mur (long) 27",
		["longwall28"] = "Mur (long) 28",
		["longwall29"] = "Mur (long) 29",
		["longwall30"] = "Mur (long) 30",
		["longwall31"] = "Mur (long) 31",
		["longwall32"] = "Mur (long) 32",
		["longwall33"] = "Mur (long) 33",
		["longwall34"] = "Mur (long) 34",
		["longwall35"] = "Mur (long) 35",
		["longwall36"] = "Mur (long) 36",
		["longwall37"] = "Mur (long) 37",
		["longwall38"] = "Mur (long) 38",
		["longwall39"] = "Mur (long) 39",
		["longwall40"] = "Mur (long) 40",
		["wall01"] = "Mur 1",
		["wall02"] = "Mur 2",
		["wall03"] = "Mur 3",
		["wall04"] = "Mur 4",
		["wall05"] = "Mur 5",
		["wall06"] = "Mur 6",
		["wall07"] = "Mur 7",
		["wall08"] = "Mur 8",
		["wall09"] = "Mur 9",
		["wall10"] = "Mur 10",
		["wall11"] = "Mur 11",
		["wall12"] = "Mur 12",
		["wall13"] = "Mur 13",
		["wall14"] = "Mur 14",
		["wall15"] = "Mur 15",
		["wall16"] = "Mur 16",
		["wall17"] = "Mur 17",
		["wall18"] = "Mur 18",
		["wall19"] = "Mur 19",
		["wall20"] = "Mur 20",
		["wall21"] = "Mur 21",
		["wall22"] = "Mur 22",
		["wall23"] = "Mur 23",
		["wall24"] = "Mur 24",
		["wall25"] = "Mur 25",
		["wall26"] = "Mur 26",
		["wall27"] = "Mur 27",
		["wall28"] = "Mur 28",
		["wall29"] = "Mur 29",
		["wall30"] = "Mur 30",
		["wall31"] = "Mur 31",
		["wall32"] = "Mur 32",
		["wall33"] = "Mur 33",
		["wall34"] = "Mur 34",
		["wall35"] = "Mur 35",
		["wall36"] = "Mur 36",
		["wall37"] = "Mur 37",
		["wall38"] = "Mur 38",
		["wall39"] = "Mur 39",
		["wall40"] = "Mur 40",
	},
	["Cuisines"] = {
		["pata_kit2_1"] = "Mandoline",
    	["pata_kit2_10"] = "Mixer",
		["pata_kit2_11"] = "Appareil à fondu",
		["pata_kit2_12"] = "Machine à café",
		["pata_kit2_13"] = "Presse Agrumes",
		["pata_kit2_14"] = "Mixer",
		["pata_kit2_15"] = "Plat",
		["pata_kit2_16"] = "Robot",
		["pata_kit2_17"] = "Farine",
		["pata_kit2_18"] = "Sucre",
		["pata_kit2_19"] = "Bol d'oeuf",
		["pata_kit2_2"] = "Assiette bois",
		["pata_kit2_20"] = "Boite a cookies",
		["pata_kit2_21"] = "Plaque Cuisson + Grille pain",
		["pata_kit2_22"] = "Cafetière",
		["pata_kit2_23"] = "Four d'appoint",
		["pata_kit2_24"] = "Poele",
		["pata_kit2_25"] = "Placard",
		["pata_kit2_26"] = "Meuble de cuisine",
		["pata_kit2_27"] = "Etagere a condiment",
		["pata_kit2_28"] = "Casserole",
		["pata_kit2_29"] = "Réfrigirateur",
		["pata_kit2_3"] = "Bouteille de persil",
		["pata_kit2_30"] = "Gasinière",
		["pata_kit2_31"] = "Combiné Four / Cafetière",
		["pata_kit2_32"] = "Chaise haute",
		["pata_kit2_33"] = "Placard 2",
		["pata_kit2_34"] = "Assiette de fromage",
		["pata_kit2_35"] = "Meuble de cuisine 2",
		["pata_kit2_36"] = "Meuble de cuisine 3",
		["pata_kit2_37"] = "Planche a découper",
		["pata_kit2_38"] = "Meuble de cuisine 3",
		["pata_kit2_39"] = "Hote de cuisine",
		["pata_kit2_4"] = "Combo d'epices",
		["pata_kit2_40"] = "Plan de travail",
		["pata_kit2_41"] = "Savon",
		["pata_kit2_42"] = "Assiettes",
		["pata_kit2_43"] = "Ustensils de cuisine",
		["pata_kit2_44"] = "Boite de rangement",
		["pata_kit2_45"] = "Cave a vin",
		["pata_kit2_46"] = "Gasinière",
		["pata_kit2_47"] = "Saladier",
		["pata_kit2_48"] = "Etagère",
		["pata_kit2_49"] = "Petit rangement de vin",
		["pata_kit2_5"] = "Plat 2",
		["pata_kit2_50"] = "Etagère",
		["pata_kit2_51"] = "Etagère 2",
		["pata_kit2_52"] = "Boite de Pringles",
		["pata_kit2_53"] = "Oréo",
		["pata_kit2_54"] = "Nutella",
		["pata_kit2_55"] = "Appareil a Raclette",
		["pata_kit2_56"] = "Assiette de charcuterie",
		["pata_kit2_57"] = "Assiette de fromage a raclette",
		["pata_kit2_58"] = "Assiette raclette",
		["pata_kit2_59"] = "Assiette raclette 2",
		["pata_kit2_6"] = "Grille pain",
		["pata_kit2_60"] = "Dosette a café",
		["pata_kit2_61"] = "Brioche Choco",
		["pata_kit2_62"] = "Boite de céréales",
		["pata_kit2_63"] = "Sachet de thé",
		["pata_kit2_64"] = "Bouteille d'eau",
		["pata_kit2_65"] = "Boite de conserve",
		["pata_kit2_66"] = "Ustensils de cuisine 2",
		["pata_kit2_67"] = "Rangement céréales",
		["pata_kit2_68"] = "Rangement thé",
		["pata_kit2_69"] = "Egoutoir",
		["pata_kit2_7"] = "Appareil a crepe",
		["pata_kit2_70"] = "Rangement a ustensils",
		["pata_kit2_71"] = "Rangement a ustensils 2",
	},
	["Salle de bain"] = {
		["pata_2bathroom1"] = "Meuble + Lavabo",
		["pata_2bathroom10"] = "Rangement papier toilette",
		["pata_2bathroom11"] = "Lavabo",
		["pata_2bathroom12"] = "Lavabo 2",
		["pata_2bathroom13"] = "Sac",
		["pata_2bathroom14"] = "Neon",
		["pata_2bathroom15"] = "Mirroir",
		["pata_2bathroom16"] = "Baignoire",
		["pata_2bathroom17"] = "Tabouret",
		["pata_2bathroom18"] = "Assiette de rangement",
		["pata_2bathroom19"] = "Serviette + Lotion",
		["pata_2bathroom2"] = "Commode",
		["pata_2bathroom20"] = "Plante",
		["pata_2bathroom21"] = "Pot de fleur",
		["pata_2bathroom22"] = "Etagere de rangement",
		["pata_2bathroom23"] = "Seche serviette",
		["pata_2bathroom24"] = "Meuble",
		["pata_2bathroom25"] = "Pot de fleur",
		["pata_2bathroom26"] = "Tablette de bain",
		["pata_2bathroom27"] = "Papier Toilette",
		["pata_2bathroom28"] = "Pot Brosse a dent",
		["pata_2bathroom29"] = "Mirroir + Rangement",
		["pata_2bathroom3"] = "Peignoir",
		["pata_2bathroom30"] = "Balance",
		["pata_2bathroom31"] = "Tabouret 2",
		["pata_2bathroom32"] = "Meuble",
		["pata_2bathroom33"] = "Support a Papier toilette",
		["pata_2bathroom34"] = "Meuble + Lavabo 2",
		["pata_2bathroom35"] = "Tapis",
		["pata_2bathroom36"] = "Tapis 2",
		["pata_2bathroom37"] = "Comestique",
		["pata_2bathroom38"] = "Douche",
		["pata_2bathroom39"] = "Comestique 2",
		["pata_2bathroom4"] = "Baignoire 2",
		["pata_2bathroom40"] = "Serviette",
		["pata_2bathroom41"] = "Douche 2",
		["pata_2bathroom42"] = "Lavabo suspendu",
		["pata_2bathroom43"] = "Toilette",
		["pata_2bathroom44"] = "Rangement Papier Toilette",
		["pata_2bathroom45"] = "Cabine de douche",
		["pata_2bathroom46"] = "Douche 3",
		["pata_2bathroom47"] = "Panier a linge",
		["pata_2bathroom48"] = "Comestique 3",
		["pata_2bathroom49"] = "Papier toilette",
		["pata_2bathroom5"] = "Lavabo 4",
		["pata_2bathroom50"] = "Range Serviette",
		["pata_2bathroom6"] = "Savon",
		["pata_2bathroom7"] = "Lavabo suspendu 2",
		["pata_2bathroom8"] = "Rangement pour toilette",
		["pata_2bathroom9"] = "Toilette 2",
	},
	["Nurserie"] = {
		["pata_nursery"] = "pata_nursery",
    	["pata_nursery10"] = "pata_nursery10",
		["pata_nursery11"] = "pata_nursery11",
		["pata_nursery12"] = "pata_nursery12",
		["pata_nursery13"] = "pata_nursery13",
		["pata_nursery14"] = "pata_nursery14",
		["pata_nursery15"] = "pata_nursery15",
		["pata_nursery16"] = "pata_nursery16",
		["pata_nursery17"] = "pata_nursery17",
		["pata_nursery18"] = "pata_nursery18",
		["pata_nursery19"] = "pata_nursery19",
		["pata_nursery2"] = "pata_nursery2",
		["pata_nursery20"] = "pata_nursery20",
		["pata_nursery21"] = "pata_nursery21",
		["pata_nursery22"] = "pata_nursery22",
		["pata_nursery23"] = "pata_nursery23",
		["pata_nursery24"] = "pata_nursery24",
		["pata_nursery25"] = "pata_nursery25",
		["pata_nursery26"] = "pata_nursery26",
		["pata_nursery27"] = "pata_nursery27",
		["pata_nursery28"] = "pata_nursery28",
		["pata_nursery29"] = "pata_nursery29",
		["pata_nursery3"] = "pata_nursery3",
		["pata_nursery30"] = "pata_nursery30",
		["pata_nursery31"] = "pata_nursery31",
		["pata_nursery32"] = "pata_nursery32",
		["pata_nursery33"] = "pata_nursery33",
		["pata_nursery34"] = "pata_nursery34",
		["pata_nursery35"] = "pata_nursery35",
		["pata_nursery36"] = "pata_nursery36",
		["pata_nursery37"] = "pata_nursery37",
		["pata_nursery38"] = "pata_nursery38",
		["pata_nursery39"] = "pata_nursery39",
		["pata_nursery4"] = "pata_nursery4",
		["pata_nursery40"] = "pata_nursery40",
		["pata_nursery41"] = "pata_nursery41",
		["pata_nursery42"] = "pata_nursery42",
		["pata_nursery43"] = "pata_nursery43",
		["pata_nursery44"] = "pata_nursery44",
		["pata_nursery45"] = "pata_nursery45",
		["pata_nursery46"] = "pata_nursery46",
		["pata_nursery47"] = "pata_nursery47",
		["pata_nursery48"] = "pata_nursery48",
		["pata_nursery49"] = "pata_nursery49",
		["pata_nursery5"] = "pata_nursery5",
		["pata_nursery50"] = "pata_nursery50",
		["pata_nursery51"] = "pata_nursery51",
		["pata_nursery52"] = "pata_nursery52",
		["pata_nursery53"] = "pata_nursery53",
		["pata_nursery54"] = "pata_nursery54",
		["pata_nursery55"] = "pata_nursery55",
		["pata_nursery56"] = "pata_nursery56",
		["pata_nursery57"] = "pata_nursery57",
		["pata_nursery58"] = "pata_nursery58",
		["pata_nursery59"] = "pata_nursery59",
	},
	["Chambre d'enfant"] = {
		["pata_toddler1"] = "pata_toddler1",
    	["pata_toddler10"] = "pata_toddler10",
		["pata_toddler11"] = "pata_toddler11",
		["pata_toddler12"] = "pata_toddler12",
		["pata_toddler13"] = "pata_toddler13",
		["pata_toddler14"] = "pata_toddler14",
		["pata_toddler15"] = "pata_toddler15",
		["pata_toddler16"] = "pata_toddler16",
		["pata_toddler17"] = "pata_toddler17",
		["pata_toddler18"] = "pata_toddler18",
		["pata_toddler19"] = "pata_toddler19",
		["pata_toddler2"] = "pata_toddler2",
		["pata_toddler20"] = "pata_toddler20",
		["pata_toddler21"] = "pata_toddler21",
		["pata_toddler22"] = "pata_toddler22",
		["pata_toddler23"] = "pata_toddler23",
		["pata_toddler24"] = "pata_toddler24",
		["pata_toddler25"] = "pata_toddler25",
		["pata_toddler26"] = "pata_toddler26",
		["pata_toddler27"] = "pata_toddler27",
		["pata_toddler28"] = "pata_toddler28",
		["pata_toddler29"] = "pata_toddler29",
		["pata_toddler3"] = "pata_toddler3",
		["pata_toddler30"] = "pata_toddler30",
		["pata_toddler31"] = "pata_toddler31",
		["pata_toddler32"] = "pata_toddler32",
		["pata_toddler33"] = "pata_toddler33",
		["pata_toddler34"] = "pata_toddler34",
		["pata_toddler35"] = "pata_toddler35",
		["pata_toddler36"] = "pata_toddler36",
		["pata_toddler37"] = "pata_toddler37",
		["pata_toddler38"] = "pata_toddler38",
		["pata_toddler39"] = "pata_toddler39",
		["pata_toddler4"] = "pata_toddler4",
		["pata_toddler40"] = "pata_toddler40",
		["pata_toddler41"] = "pata_toddler41",
		["pata_toddler42"] = "pata_toddler42",
		["pata_toddler43"] = "pata_toddler43",
		["pata_toddler44"] = "pata_toddler44",
		["pata_toddler45"] = "pata_toddler45",
		["pata_toddler46"] = "pata_toddler46",
		["pata_toddler47"] = "pata_toddler47",
		["pata_toddler48"] = "pata_toddler48",
		["pata_toddler49"] = "pata_toddler49",
		["pata_toddler5"] = "pata_toddler5",
		["pata_toddler50"] = "pata_toddler50",
		["pata_toddler51"] = "pata_toddler51",
		["pata_toddler52"] = "pata_toddler52",
		["pata_toddler53"] = "pata_toddler53",
		["pata_toddler54"] = "pata_toddler54",
		["pata_toddler55"] = "pata_toddler55",
	},
	["Repas de Noël"] = {
		["pata_christmasfood1"] = "Chocolat Chaud + Marshmallow",
		["pata_christmasfood10"] = "Pain d'épice",
		["pata_christmasfood2"] = "Flocon de neige",
		["pata_christmasfood3"] = "Buche de Noël",
		["pata_christmasfood4"] = "Hamburger",
		["pata_christmasfood5"] = "Repas",
		["pata_christmasfood6"] = "Cupcake",
		["pata_christmasfood7"] = "Boisson",
		["pata_christmasfood8"] = "Cupcake Sapin",
		["pata_christmasfood9"] = "Maison en pain d'épice",
	},
}

function MainMenu.Props.CreatePropsListMenu(listname, list, menuId)
	local previewing = false
	local currentProp = nil
	local realList = {}

	local menu = Menus:CreateSub(menuId, listname, "default")

	for k, v in Table.PairsByKeys(list) do
		table.insert(realList, { model = k, displayName = v })
	end

	Menus:CreateThread(menu, function()
        Menus:IsVisible(menu, function()
            for _, data in pairs(realList) do
                Menus:AddButton(data.displayName, false, "", "", function()
					ClientModules.World.Decoration:Create(data.model, GetEntityCoords(PlayerPedId(), true) + GetEntityForwardVector(PlayerPedId()) * 2.0)
                end)
            end
        end)
    end)

	Menus:OnOpen(menu, function()
		previewing = true

		Citizen.CreateThread(function()
			local propCoords = GetEntityCoords(PlayerPedId(), true) + GetEntityForwardVector(PlayerPedId()) * 2.0
			local ped = PlayerPedId()

			while previewing == true do
				Citizen.Wait(0)

				propCoords = GetEntityCoords(ped, true) + GetEntityForwardVector(ped) * 2.0

				if currentProp ~= nil then
					SetEntityCoords(currentProp, propCoords.x, propCoords.y, propCoords.z, true, false, false, false)
					SetEntityHeading(currentProp, GetEntityHeading(ped))
				end
			end
		end)
	end)

	Menus:OnIndexChange(menu, function (index)
		local coords = GetEntityCoords(PlayerPedId(), true) + GetEntityForwardVector(PlayerPedId()) * 2.0

		if currentProp ~= nil then
			DeleteEntity(currentProp)
		end

		currentProp = CreateObject(realList[index].model, coords.x, coords.y, coords.z, false, false, false)
		SetEntityCollision(currentProp, false, false)
		SetEntityAlpha(currentProp, 50, false)
    end)

    Menus:OnClose(menu, function()
		if currentProp ~= nil then
			DeleteEntity(currentProp)
		end

		previewing = false
		currentProp = nil
	end)

	return menu
end

MainMenu.Props.Create = function()
    MainMenu.Props.Main = Menus:CreateSub(MainMenu.Main, "Props", "default")
    MainMenu.Props.Settings.Create()
    MainMenu.Props.List.Create()

	local listsMenus = {}
	local max_allowed_props = 0

	for k, v in pairs(lists) do
		table.insert(listsMenus, {
			menu = MainMenu.Props.CreatePropsListMenu(k, v, MainMenu.Props.Main),
			name = k,
		})
	end

	Menus:OnOpen(MainMenu.Props.Main, function()
		max_allowed_props = ClientModules.World.Decoration:GetMaxAllowedProps()
	end)

    Menus:CreateThread(MainMenu.Props.Main, function()
        Menus:IsVisible(MainMenu.Props.Main, function()
            Menus:AddButton(
				("Mes props (%d/%d)"):format(ClientModules.World.Decoration:GetCurrentDecorationSize(), max_allowed_props),
				false, "", "chevron_right", function()end, MainMenu.Props.List.Main
			)

            Menus:AddSeparator("Créer un prop")

            Menus:AddButton("Chercher un modèle", false, "", "chevron_right", function()
                UI:OpenURL(("https://forge.plebmasters.de/objects?search=%s"):format(Utils.KeyboardInput("Recherche", 100, "")))
            end)

            Menus:AddButton("Modèle custom", false, "", "", function()
				ClientModules.World.Decoration:Create(Utils.KeyboardInput("Modèle", 100, ""), GetEntityCoords(PlayerPedId(), true) + GetEntityForwardVector(PlayerPedId()) * 2.0)
            end)

            Menus:AddSeparator("Listes de props")

			for k, v in pairs(listsMenus) do
				Menus:AddButton(v.name, false, "", "chevron_right", function()end, v.menu)
			end

        end)
    end)
end
